name: pyjviz
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rdflib
  - graphviz
  - python-graphviz
  - pandas
  - pandas-flavor
  - black
  - mypy
  - flake8
  - mkdocs
  - pre-commit
  - mkdocs-material
  - mkdocstrings
  - pymdown-extensions
